### ISSUE TITLE
Create meta install yml

### ISSUE THREAD

**Issue by takayukioda** [takayukioda/ansible-initialize#1]
Lots of install files contains same template

``` yaml
- name: Install {{ pkg }}
  apt:
    pkg: {{ pkg }}
    state: latest
```

Make meta yaml file so you can add package install by adding new line to main.yml like below

``` yaml
- include: install.yml
  var:
    pkg: nfs
```
